general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 6
    brightness = 0.65
}

label {
    monitor =
    text = $TIME

    color = rgba(235, 201, 154, 1.0)
    font_size = 64
    font_family = JetBrainsMono Nerd Font

    position = 0, 100
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B"

    color = rgba(143, 145, 135, 1.0)
    font_size = 13
    font_family = JetBrainsMono Nerd Font

    position = 0, 45
    halign = center
    valign = center
}

input-field {
    monitor =

    size = 360, 54
    outline_thickness = 1

    inner_color = rgba(16, 26, 40, 0.90)
    outer_color = rgba(43, 52, 65, 1.0)
    font_color = rgba(235, 201, 154, 1.0)

    check_color = rgba(47, 143, 128, 1.0)
    fail_color = rgba(198, 94, 73, 1.0)

    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true

    fade_on_empty = false

    rounding = 8

    position = 0, -45
    halign = center
    valign = center
}
