general {
    hide_cursor = true
    ignore_empty_input = true
}

background {
    monitor =
    path = screenshot

    blur_passes = 2
    blur_size = 6
    brightness = 0.65
}

input-field {
    monitor =

    size = 320, 52
    outline_thickness = 0

    dots_size = 0.22
    dots_spacing = 0.25
    dots_center = true

    inner_color = rgba(3, 20, 50, 0.88)
    font_color = rgba(231, 196, 152, 1.0)

    check_color = rgba(38, 130, 114, 1.0)
    fail_color = rgba(87, 27, 14, 1.0)

    fade_on_empty = false
    placeholder_text = <i>password</i>
    fail_text = <i>$FAIL</i>

    rounding = 0

    position = 0, -20
    halign = center
    valign = center
}