# Font
font_family JetBrainsMono Nerd Font
font_size 12.5

# Window
window_padding_width 10
placement_strategy center

# Main colors
background #031432
foreground #e7c498

selection_background #268272
selection_foreground #031432

cursor #b3571f
cursor_text_color #031432

url_color #268272

# Borders used by kitty splits/tabs
active_border_color #b3571f
inactive_border_color #2c403e
bell_border_color #571b0e

# Normal ANSI colors
color0  #170e14
color1  #8f3428
color2  #268272
color3  #b87932
color4  #315f8c
color5  #89536a
color6  #409589
color7  #d4b993

# Bright ANSI colors
color8  #625d58
color9  #c65b24
color10 #53aa96
color11 #e1aa61
color12 #5681ac
color13 #b46f82
color14 #76c4b2
color15 #f1dcc0

# Behaviour
enable_audio_bell no
confirm_os_window_close 0
