# Font
font_family JetBrainsMono Nerd Font
font_size 12.5

# Window
window_padding_width 10
placement_strategy center

# Main colors

background #07111F
foreground #EBC99A

selection_background #182230
selection_foreground #EBC99A

cursor #C5662A
cursor_text_color #07111F

url_color #2F8F80

# Borders used by kitty splits/tabs

active_border_color #C5662A
inactive_border_color #2B3441
bell_border_color #C65E49

# Normal ANSI

color0  #182230
color1  #C65E49
color2  #4F9180
color3  #D49A57
color4  #557A9A
color5  #9A6678
color6  #2F8F80
color7  #C8A982

# Bright ANSI

color8  #58616A
color9  #DE735C
color10 #70AA98
color11 #E8B66F
color12 #7195B3
color13 #B98596
color14 #63B3A3
color15 #EBC99A

# Behaviour
enable_audio_bell no
confirm_os_window_close 0

# Background
background_opacity 1.0
